scalaVersion := "2.13.4"
organization := "com.lihaoyi"
name := "requests-scala"
libraryDependencies += "com.lihaoyi" %% "geny" % "0.6.2"
libraryDependencies += "com.lihaoyi" %% "utest" % "0.7.5" % Test
libraryDependencies += "com.lihaoyi" %% "ujson" % "1.2.2" % Test
testFrameworks := Seq(new TestFramework("utest.runner.Framework"))
Compile / unmanagedSourceDirectories += baseDirectory.value / "requests" / "src"
Test / unmanagedSourceDirectories += baseDirectory.value / "requests" / "test" / "src"
Compile / scalacOptions ++= Seq("-feature", "-deprecation")
